In [1]:
import pandas as pd 
import numpy as np

In [3]:
df  =  pd.read_csv("iris.csv")
print(df, type(df))

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns] <class 'pandas.DataFrame'>

In [6]:
print(df.tail())
print(df.info())

RangeIndex(start=0, stop=150, step=1)
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 9.1 KB
None

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 9.1 KB
None

In [28]:
df.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [9]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [10]:
df.sample(1)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
45  46            4.8           3.0            1.4           0.3  Iris-setosa

In [12]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [87]:
df.nunique()

Id               150
SepalLengthCm     35
SepalWidthCm      23
PetalLengthCm     43
PetalWidthCm      22
Species            3
dtype: int64

In [16]:
df.shape
df.columns
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

In [19]:
df["SepalLengthCm"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [84]:
# print(df.mean)
# print(df.std)
df["SepalLengthCm"]>7.5

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: SepalLengthCm, Length: 150, dtype: bool

In [149]:
filtered = df[(df["SepalLengthCm"]>7) & (df["Species"] == "Iris-virginica")]
# print(filtered.shape)
print(filtered.head)

<bound method NDFrame.head of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
102  103            7.1           3.0            5.9           2.1
105  106            7.6           3.0            6.6           2.1
107  108            7.3           2.9            6.3           1.8
109  110            7.2           3.6            6.1           2.5
117  118            7.7           3.8            6.7           2.2
118  119            7.7           2.6            6.9           2.3
122  123            7.7           2.8            6.7           2.0
125  126            7.2           3.2            6.0           1.8
129  130            7.2           3.0            5.8           1.6
130  131            7.4           2.8            6.1           1.9
131  132            7.9           3.8            6.4           2.0
135  136            7.7           3.0            6.1           2.3

            Species  petal_ratio
102  Iris-virginica     2.366667
105  Iris-virginica     2.533333
107  Iris-virginica     2.517241
109  Iris-virginica     2.000000
117  Iris-virginica     2.026316
118  Iris-virginica     2.961538
122  Iris-virginica     2.750000
125  Iris-virginica     2.250000
129  Iris-virginica     2.400000
130  Iris-virginica     2.642857
131  Iris-virginica     2.078947
135  Iris-virginica     2.566667  >

In [135]:
sum  = df["SepalLengthCm"].mean()
std_dev =df["SepalLengthCm"].std()
max  = df["SepalWidthCm"].max()
print(sum)
print(std_dev)
print(max)

5.843333333333334
0.8280661279778629
4.4

In [138]:
df["petal_ratio"] = df["SepalLengthCm"]/df["SepalWidthCm"]
print(df.groupby("Species")["petal_ratio"].mean().round(3))

Species
Iris-setosa        1.475
Iris-versicolor    2.160
Iris-virginica     2.230
Name: petal_ratio, dtype: float64