In [2]:
import pandas as pd

In [3]:
info ={
    "name" :["krish","ashok","bisen", "rahul"],
    "cgpa" :["9.55","8.5", "9.0", "9.8"]
}

df = pd.DataFrame(info)
print(df)

    name  cgpa
0  krish  9.55
1  ashok   8.5
2  bisen   9.0
3  rahul   9.8

In [4]:
s = pd.Series([1,2,3,4,5,67,8])
print(s)
print(type(s))

0     1
1     2
2     3
3     4
4     5
5    67
6     8
dtype: int64
<class 'pandas.Series'>

In [6]:
s = pd.Series([6,28,33,45,58,67,80], index=["ram","sham", "rahul", "krishna", "raju", "parul", "vihay"])
print(s)

ram         6
sham       28
rahul      33
krishna    45
raju       58
parul      67
vihay      80
dtype: int64

In [7]:
print(s["krishna"])
print(s["sham"])

45
28

In [8]:
print(s.index)

Index(['ram', 'sham', 'rahul', 'krishna', 'raju', 'parul', 'vihay'], dtype='str')

In [9]:
s1 = pd.Series([5,6,7,8,9])
s2 = pd.Series([5,6,7,8,9])
print(s1 + s2 )

0    10
1    12
2    14
3    16
4    18
dtype: int64

In [10]:
s1[0] =100
print(s1)

0    100
1      6
2      7
3      8
4      9
dtype: int64

In [11]:
print(s1.drop(0))

1    6
2    7
3    8
4    9
dtype: int64

In [12]:
# Data Frame 
info ={
    "name":["krish", "sham", "booob"],
    "age" :[23,34,54],
    "gpa" :[9.8,8.9, 9.0]
}
qw = pd.DataFrame(info)
print(qw)
print(type(qw))
print(qw.index)
print(qw.columns)

    name  age  gpa
0  krish   23  9.8
1   sham   34  8.9
2  booob   54  9.0
<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'gpa'], dtype='str')

In [13]:
qw  =pd.DataFrame([["ansh",43],["boob",54],["krish",78]],columns=["name","age"])
print(qw)

    name  age
0   ansh   43
1   boob   54
2  krish   78

In [14]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr,columns =["a","b","c"])
print(df)

   a  b  c
0  1  2  3
1  4  5  6

In [15]:
# csv data
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [16]:
# csv data
df = pd.read_json("employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [17]:
# method
# print(df.head())
# print(df.tail())

In [18]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [19]:
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [20]:
# cleaning the data 

df.isna().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [21]:
# df.dropna()
# df.dropna(axis=1)colunm drop


cleaned_data =df.copy()

age_mean  = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [22]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [23]:
#  handle the duplecate 
df.drop_duplicates(inplace = True )

In [24]:
df.dtypes
df2 =df.copy()
df2 = df2.fillna(0)
df2["age"] =df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [25]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [26]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [27]:
aqi_data =pd.read_csv("global air pollution dataset.csv")
aqi_data

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

In [28]:
date_str  = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [29]:
# aqi_data[""].dtypes

aqi_data.columns

Index(['Country', 'City', 'AQI Value', 'AQI Category', 'CO AQI Value',
       'CO AQI Category', 'Ozone AQI Value', 'Ozone AQI Category',
       'NO2 AQI Value', 'NO2 AQI Category', 'PM2.5 AQI Value',
       'PM2.5 AQI Category'],
      dtype='str')

In [30]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [31]:
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["country"].str.contains("india", case = False)

0     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [32]:
df2 = df.copy()
df2["tax"] =df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [33]:
gender_map  = {"male" : "m",
               "Unknown" : "U",
               "Female" : "f"
            
              }
df2["gender"].map(gender_map)

0     NaN
2       f
3       U
4       f
5     NaN
6       f
7     NaN
8       f
9     NaN
10    NaN
Name: gender, dtype: str

In [34]:
gender_map  = {"male" : "m",
               "Unknown" : "U",
               "Female" : "f"
            
              }
df2["gender"].map(gender_map)

0     NaN
2       f
3       U
4       f
5     NaN
6       f
7     NaN
8       f
9     NaN
10    NaN
Name: gender, dtype: str

In [37]:
df2.assign(new_income = df2["income"]* 1.1)

    id          name   age country   gender   income  tax  new_income
0    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%     68200.0
3    3          Alex   NaN     USA  Unknown  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%         NaN
5    5        Li Wei  27.0   China     Male  51000.0  20%     56100.0
6    6           NaN  45.0   India   Female  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%     63800.0

In [39]:
df2["country"]= df2["country"].replace("USA" , "us")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0      us     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN      us  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0      us   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0      us      NaN  58000.0  20%

In [42]:
df2.columns = ['Id','Name','Age','Country','Gender','Income', 'Tax','New_Income']
df2 = df2.rename(columns={"Income": "salary"})

ValueError: Length mismatch: Expected axis has 7 elements, new values have 8 elements