In [ ]:
import pandas as pd 
from sklearn.metrics import precision_score, accuracy_score , recall_score , f1_score , confusion_matrix
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv(f'heart.csv')
display(df.head())


X =  df.drop("target", axis = 1 )
y = df["target"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2, random_state = 42 )

from sklearn.preprocessing import StandardScaler

scaller = StandardScaler()
X_train_scalled= scaller.fit_transform(X_train)
X_test_scalled = scaller.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier

knn_classifier =  KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_scalled, y_train)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

KNeighborsClassifier()

In [2]:
y_pred  =  knn_classifier.predict(X_test_scalled)
# evaluation
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy _score", accuracy_score(y_test, y_pred))
print("recal _score",recall_score(y_test, y_pred))
print("precision_score", precision_score(y_test, y_pred))

[[79 23]
 [11 92]]
accuracy _score 0.8341463414634146
recal _score 0.8932038834951457
precision_score 0.8

In [3]:
# for k = 9 

import pandas as pd 
from sklearn.metrics import precision_score, accuracy_score , recall_score , f1_score , confusion_matrix
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv(f'heart.csv')
display(df.head())


X =  df.drop("target", axis = 1 )
y = df["target"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2, random_state = 42 )

from sklearn.preprocessing import StandardScaler

scaller = StandardScaler()
X_train_scalled= scaller.fit_transform(X_train)
X_test_scalled = scaller.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier

knn_classifier =  KNeighborsClassifier(n_neighbors=9)
knn_classifier.fit(X_train_scalled, y_train)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

KNeighborsClassifier(n_neighbors=9)

In [4]:
y_pred  =  knn_classifier.predict(X_test_scalled)
# evaluation
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy _score", accuracy_score(y_test, y_pred))
print("recal _score",recall_score(y_test, y_pred))
print("precision_score", precision_score(y_test, y_pred))

[[80 22]
 [11 92]]
accuracy _score 0.8390243902439024
recal _score 0.8932038834951457
precision_score 0.8070175438596491

In [27]:

# cross vallidationn

from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier()
param_grid = {"n_neighbors":[3,5,7,9]}
classifierCV =  GridSearchCV(
    classifier,
    param_grid,
    cv = 5,
    scoring ="precision"
)
X_test_scalled = scaller.transform(X_test)
classifierCV.fit(X_train_scalled, y_train )

y_pred =  classifierCV.predict(X_test_scalled)

In [28]:
print("recall score  = ", recall_score(y_test,y_pred))
print("accuracy score =", accuracy_score(y_test,y_pred))
print("precision score ", precision_score(y_test,y_pred))

print("best_param ", classifierCV.best_params_)

recall score  =  0.9514563106796117
accuracy score = 0.9365853658536586
precision score  0.9245283018867925
best_param  {'n_neighbors': 3}

In [31]:
from sklearn.pipeline import Pipeline 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2, random_state = 42 )

In [35]:
pipeline = Pipeline([
    ("scaler" , StandardScaler()),
    ("knn", KNeighborsClassifier())

])
param_grid = {"Knn__n_neighors" : [3,5,7,9]}

clssifierCV = GridSearchCV(
    pipeline,
    param_grid,
    cv =5 ,
    scoring= "recall"
)

classifierCV.fit(X_train, y_train)
y_pred = classifierCV.predict(X_test)

In [36]:
print("recall score  = ", recall_score(y_test,y_pred))
print("accuracy score =", accuracy_score(y_test,y_pred))
print("precision score ", precision_score(y_test,y_pred))

print("best_param ", classifierCV.best_params_)

recall score  =  0.912621359223301
accuracy score = 0.9024390243902439
precision score  0.8952380952380953
best_param  {'n_neighbors': 3}